# Generated by Django 5.1 on 2025-04-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="applied_at",
            new_name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruitment.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruitment.position",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("reviewing", "Under Review"),
                    ("interview", "Interview Scheduled"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
