# Generated by Django 5.1 on 2025-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0004_rename_applied_at_application_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
