# Generated by Django 5.1 on 2025-04-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_position_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
