# Generated by Django 5.1 on 2025-05-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_applicationstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone', 'Phone Interview'), ('video', 'Video Interview'), ('technical', 'Technical Interview'), ('onsite', 'On-site Interview'), ('assessment', 'Assessment')], default='onsite', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
